/**
 * Wedding configurations keyed by URL slug.
 *
 * Slugs:
 *   default  → Көркембек & Ақбота (main, Kazakh)
 *   ularbek  → Б. Ұлбарбек & Қ. Айсымбат (Kazakh)   → /ularbek
 *   mn       → Б. Уларбек & Х. Айсымбат (Mongolian)  → /mn
 */

const configs = {
  // ──────────────────────────────────────────────
  // DEFAULT  –  Көркембек & Ақбота (Казахша)
  // ──────────────────────────────────────────────
  default: {
    data: {
      title: "Көркембек & Ақбота тойы",
      description: "Көркембек пен Ақбота — сізді тойға шақырады.",
      groomName: "Көркембек",
      brideName: "Ақбота",
      parentGroom: "Махаббат",
      parentBride: "Гүлмайра",
      date: "2026-08-22",
      time: "16:00",
      location: "Алтынел мейрамханасы",
      address: "Қоянды, Алтынел мейрамханасы",
      texts: {
        eventOwnersTitle: "Той иелері:",
        eventProgramTitle: "Той салтанатының бағдарламасы",
        eventProgramSubtitle:
          "Біз сіздерді махаббат жолымыздың басталуының куәгері болуға шақырамыз",
        heroGreeting: "Құрметті қонақтар!",
        heroBanner: "Біздің бақытты күнімізбен бөлісіңіз!",
        heroInvitePrefix: "Cіздерді балаларымыз",
        heroInviteSuffix:
          "Үйлену тойына арналған салтанатты дастарханымыздың қадірлі қонағы болуға шақырамыз!",
        zoomHint: "Үлкейту",
        invitationButton: "Шақыруды ашу",
        giftsTagline: "Hadiah Pernikahan",
        giftsTitle: "Berikan Hadiah",
        giftsInsyaAllahArabic: "إن شاء الله",
        giftsMainMessage:
          "Insya Allah, Kami Akan Menyalurkan Semua Hadiah yang Diberikan ke Beberapa Masjid dan Lembaga yang Membutuhkan",
        giftsDuaArabic: "جزاكم الله خيرا وبارك الله فيكم",
        giftsDuaLatin: "Jazakumullahu khairan, Barakallah fiikum",
        copy: "Copy",
        copied: "Copied!",
        galleryTagline: "Сәттер жинағы",
        galleryTitle: "Фотогалерея",
        countdown: {
          days: "күн",
          hours: "сағ",
          minutes: "мин",
          seconds: "сек",
        },
        locationTitle: "Мекенжай",
        mapButtonText: "Картаны көру",
        wishSuccess: "Тілегіңіз сәтті жіберілді",
        rsvpSuccess: "Қатысу жауабы жіберілді",
        nameLabel: "Сіздің атыңыз",
        namePlaceholder: "Атыңызды енгізіңіз...",
        wishLabel: "Тілегіңіз",
        wishPlaceholder: "Тілегіңізді жазыңыз...",
        rsvpAttending: "Қатысамын",
        rsvpNotAttending: "Қатыса алмаймын",
        rsvpUncertain: "Белгісіз",
        submit: "Жіберу",
        submitting: "Жіберілуде...",
        errorName: "Атыңызды енгізіңіз",
        errorWishOrRsvp: "Тілегіңізді немесе қатысу жауабын енгізіңіз",
        errorFetch: "Тілектерді жүктеу кезінде қате шықты",
        errorSubmit: "Деректерді жіберу кезінде қате шықты",
        imageError: "Сурет жүктелмеді",
        galleryEmpty: "Галерея суреттерін config ішінде толтырыңыз.",
        navHome: "Басты бет",
        navEvent: "Іс-шара",
        navLocation: "Мекенжай",
      },
      media: {
        appBackground: "/images/Ai.jfif",
        landingBackground: "/images/Ai.jfif",
        landingCover: "/images/Ai.jfif",
        heroMainPhoto: "/images/Ai.jfif",
        videoSlides: ["/images/Ai.jfif", "/images/Ai.jfif"],
        preloaderPriority: ["/images/Ai.jfif", "/images/Ai.jfif"],
        preloaderGallery: [
          "/images/Saya/3.JPEG",
          "/images/Saya/4.JPEG",
          "/images/Saya/5.JPEG",
          "/images/Saya/6.JPEG",
          "/images/Saya/7.JPEG",
          "/images/Saya/8.JPEG",
          "/images/Saya/9.JPEG",
          "/images/Saya/11.jpg",
          "/images/Saya/12.jpg",
          "/images/Saya/13.jpg",
        ],
        galleryPhotos: [
          {
            id: 1,
            src: "/images/Ai.jfif",
            alt: "Сурет-1",
            description: "Сурет-1",
            mode: "cover",
          },
          {
            id: 2,
            src: "/images/ai2.jfif",
            alt: "Сурет-2",
            description: "Сурет-2",
            mode: "cover",
          },
          {
            id: 3,
            src: "/images/Ai.jfif",
            alt: "Сурет-3",
            description: "Сурет-3",
            mode: "cover",
          },
          {
            id: 4,
            src: "/images/ai2.jfif",
            alt: "Сурет-4",
            description: "Сурет-4",
            mode: "cover",
          },
          {
            id: 5,
            src: "/images/Ai.jfif",
            alt: "Сурет-5",
            description: "Сурет-5",
            mode: "cover",
          },
          {
            id: 6,
            src: "/images/ai2.jfif",
            alt: "Сурет-6",
            description: "Сурет-6",
            mode: "contain",
          },
        ],
      },
      calendar: {
        monthLabel: "Тамыз",
        daysOfWeek: ["Дүй", "Сей", "Сәр", "Бей", "Жұм", "Сен", "Жек"],
        firstDayOffset: 5,
        markedDate: 22,
      },
      maps_url: "https://2gis.kz/astana/geo/70000001066179111",
      maps_embed:
        "https://www.openstreetmap.org/export/embed.html?bbox=71.6205%2C51.2732%2C71.6271%2C51.2763&layer=mapnik&marker=51.274762%2C71.623814",
      favicon: "/images/favicon.ico",
      agenda: [
        {
          title: "Той",
          date: "2026-08-22",
          startTime: "17:00",
          endTime: "00:00",
          location: "Алтынел мейрамханасы",
          address: "Қоянды, Алтынел мейрамханасы",
        },
      ],
      audio: {
        src: "/audio/toi.mp3",
        title: "Көңілді әуен",
        autoplay: true,
        loop: true,
        toastDuration: 3000,
      },
      gifts: {
        accounts: [
          {
            bank: "Kaspi Bank",
            accountName: "Korkembek A.",
            accountNumber: "0000 0000 0000 0000",
          },
        ],
      },
      shareImages: {
        ogImage: "/images/Ai.jfif",
        thumbnail: "/images/ai2.jfif",
        couplePhoto: "/images/Ai.jfif",
        banner: "/images/ai2.jfif",
        invitation: "/images/Ai.jfif",
      },
    },
  },

  // ──────────────────────────────────────────────
  // SLUG: ularbek  –  Ұлбарбек & Айсымбат (Казахша)
  // URL:  /ularbek
  // ──────────────────────────────────────────────
  ularbek: {
    data: {
      title: "Б. Ұлбарбек пен Қ. Айсымбат тойы",
      description: "Б. Ұлбарбек пен Қ. Айсымбат — сізді тойға шақырады.",
      groomName: "Б. Ұлбарбек",
      brideName: "Қ. Айсымбат",
      parentGroom: "Бекболат",
      parentBride: "Баршагүл",
      date: "2026-06-24",
      time: "18:00",
      location: '"Sky Palace" тойханасы',
      address: 'Монгол, "Sky Palace" тойханасы',
      texts: {
        eventOwnersTitle: "Той иелері:",
        eventProgramTitle: "Той салтанатының бағдарламасы",
        eventProgramSubtitle:
          "Біз сіздерді махаббат жолымыздың басталуының куәгері болуға шақырамыз",
        heroGreeting: "Құрметті қонақтар!",
        heroBanner: "Біздің бақытты күнімізбен бөлісіңіз!",
        heroInvitePrefix: "Cіздерді балаларымыз",
        heroInviteSuffix:
          "Үйлену тойына арналған салтанатты дастарханымыздың қадірлі қонағы болуға шақырамыз!",
        zoomHint: "Үлкейту",
        invitationButton: "Шақыруды ашу",
        giftsTagline: "Той сыйлықтары",
        giftsTitle: "Сыйлық беру",
        giftsInsyaAllahArabic: "إن شاء الله",
        giftsMainMessage:
          "Сіздердің жылы тілектеріңіз бен қолдауларыңыз bizim үшін ең үлкен сыйлық.",
        giftsDuaArabic: "جزاكم الله خيرا وبارك الله فيكم",
        giftsDuaLatin: "Jazakumullahu khairan, Barakallah fiikum",
        copy: "Көшіру",
        copied: "Көшірілді!",
        galleryTagline: "Сәттер жинағы",
        galleryTitle: "Фотогалерея",
        countdown: {
          days: "күн",
          hours: "сағ",
          minutes: "мин",
          seconds: "сек",
        },
        locationTitle: "Мекенжай",
        mapButtonText: "Картаны көру",
        wishSuccess: "Тілегіңіз сәтті жіберілді",
        rsvpSuccess: "Қатысу жауабы жіберілді",
        nameLabel: "Сіздің атыңыз",
        namePlaceholder: "Атыңызды енгізіңіз...",
        wishLabel: "Тілегіңіз",
        wishPlaceholder: "Тілегіңізді жазыңыз...",
        rsvpAttending: "Қатысамын",
        rsvpNotAttending: "Қатыса алмаймын",
        rsvpUncertain: "Белгісіз",
        submit: "Жіберу",
        submitting: "Жіберілуде...",
        errorName: "Атыңызды енгізіңіз",
        errorWishOrRsvp: "Тілегіңізді немесе қатысу жауабын енгізіңіз",
        errorFetch: "Тілектерді жүктеу кезінде қате шықты",
        errorSubmit: "Деректерді жіберу кезінде қате шықты",
        imageError: "Сурет жүктелмеді",
        galleryEmpty: "Галерея суреттерін config ішінде толтырыңыз.",
        navHome: "Басты бет",
        navEvent: "Іс-шара",
        navLocation: "Мекенжай",
      },
      media: {
        appBackground: "/images/Ai.jfif",
        landingBackground: "/images/Ai.jfif",
        landingCover: "/images/Ai.jfif",
        heroMainPhoto: "/images/Ai.jfif",
        videoSlides: ["/images/Ai.jfif", "/images/Ai.jfif"],
        preloaderPriority: ["/images/Ai.jfif", "/images/Ai.jfif"],
        preloaderGallery: [],
        galleryPhotos: [],
      },
      calendar: {
        monthLabel: "Маусым",
        daysOfWeek: ["Дүй", "Сей", "Сәр", "Бей", "Жұм", "Сен", "Жек"],
        firstDayOffset: 0,
        markedDate: 24,
      },
      maps_url: "https://maps.app.goo.gl/iC2PFvMY3NKeVczk7",
      maps_embed:
        "https://www.openstreetmap.org/export/embed.html?bbox=89.9139171%2C48.9600524%2C89.9339171%2C48.9720524&layer=mapnik&marker=48.9660524%2C89.9239171",
      favicon: "/images/favicon.ico",
      agenda: [
        {
          title: "Той",
          date: "2026-06-24",
          startTime: "18:00",
          endTime: "00:00",
          location: '"Sky Palace" тойханасы',
          address: 'Монгол, "Sky Palace" тойханасы',
        },
      ],
      audio: {
        src: "/audio/toi.mp3",
        title: "Көңілді әуен",
        autoplay: true,
        loop: true,
        toastDuration: 3000,
      },
      gifts: {
        accounts: [
          {
            bank: "Kaspi Bank",
            accountName: "Bekbolat",
            accountNumber: "0000 0000 0000 0000",
          },
        ],
      },
      shareImages: {
        ogImage: "/images/Ai.jfif",
        thumbnail: "/images/ai2.jfif",
        couplePhoto: "/images/Ai.jfif",
        banner: "/images/ai2.jfif",
        invitation: "/images/Ai.jfif",
      },
    },
  },

  // ──────────────────────────────────────────────
  // SLUG: mn  –  Уларбек & Айсымбат (Монгол хэл)
  // URL:  /mn
  // ──────────────────────────────────────────────
  mn: {
    data: {
      title: "Б. Уларбек & Х. Айсымбат-ын хурим",
      description:
        "Б. Уларбек ба Х. Айсымбат хуримынхаа баяраар та бүхнийг урьж байна.",
      groomName: "Б. Уларбек",
      brideName: "Х. Айсымбат",
      parentGroom: "Бекболат",
      parentBride: "Баршагүл",
      date: "2026-06-24",
      time: "18:00",
      location: '"Sky Palace" Хуримын ордон',
      address: 'Монгол, Баян-Өлгий, "Sky Palace" Хуримын ордон',
      texts: {
        eventOwnersTitle: "Хуримын эзэд:",
        eventProgramTitle: "Хуримын хөтөлбөр",
        eventProgramSubtitle:
          "Бид та бүхнийг хайрын замналынхаа гэрч болохыг урьж байна",
        heroGreeting: "Хүндэт зочид оо!",
        heroBanner: "Манай аз жаргалтай өдрийг хамтдаа тэмдэглэцгээе!",
        heroInvitePrefix: "Та бүхнийг",
        heroInviteSuffix: "хуримын ёслол баярт хүрэлцэн ирэхийг урьж байна!",
        zoomHint: "Томруулах",
        invitationButton: "Урилга нээх",
        giftsTagline: "Хуримын бэлэг",
        giftsTitle: "Бэлэг дурсгал",
        giftsInsyaAllahArabic: "إن شاء الله",
        giftsMainMessage:
          "Та бүхний дулаан мэндчилгээ болон дэмжлэг бидний хамгийн үнэтэй бэлэг юм.",
        giftsDuaArabic: "جزاكم الله خيرا وبارك الله فيكم",
        giftsDuaLatin: "Jazakumullahu khairan, Barakallah fiikum",
        copy: "Хуулах",
        copied: "Хуулагдлаа!",
        galleryTagline: "Дурсамжийн мөчүүд",
        galleryTitle: "Фото цомог",
        countdown: {
          days: "өдөр",
          hours: "цаг",
          minutes: "мин",
          seconds: "сек",
        },
        locationTitle: "Хаяг",
        mapButtonText: "Газрын зургийг харах",
        wishSuccess: "Таны ерөөл хүсэл амжилттай илгээгдлээ",
        rsvpSuccess: "Оролцох хариулт илгээгдлээ",
        nameLabel: "Таны нэр",
        namePlaceholder: "Нэрээ оруулна уу...",
        wishLabel: "Ерөөл хүсэл",
        wishPlaceholder: "Ерөөлөө бичнэ үү...",
        rsvpAttending: "Оролцоно",
        rsvpNotAttending: "Оролцохгүй",
        rsvpUncertain: "Тодорхойгүй",
        submit: "Илгээх",
        submitting: "Илгээж байна...",
        errorName: "Нэрээ оруулна уу",
        errorWishOrRsvp: "Ерөөл хүсэл эсвэл оролцох хариулт оруулна уу",
        errorFetch: "Хүслийн жагсаалтыг татаж авахад алдаа гарлаа",
        errorSubmit: "Мэдээлэл илгээхэд алдаа гарлаа",
        imageError: "Зургийг ачааллаж чадсангүй",
        galleryEmpty: "Зургийн цомгийг config-д нэмнэ үү.",
        navHome: "Нүүр",
        navEvent: "Арга хэмжээ",
        navLocation: "Байршил",
      },
      media: {
        appBackground: "/images/Ai.jfif",
        landingBackground: "/images/Ai.jfif",
        landingCover: "/images/Ai.jfif",
        heroMainPhoto: "/images/Ai.jfif",
        videoSlides: ["/images/Ai.jfif", "/images/Ai.jfif"],
        preloaderPriority: ["/images/Ai.jfif", "/images/Ai.jfif"],
        preloaderGallery: [],
        galleryPhotos: [],
      },
      calendar: {
        monthLabel: "6-р сар",
        daysOfWeek: ["Дав", "Мяг", "Лха", "Пүр", "Баа", "Бям", "Ням"],
        firstDayOffset: 0,
        markedDate: 24,
      },
      maps_url: "https://maps.app.goo.gl/iC2PFvMY3NKeVczk7",
      maps_embed:
        "https://www.openstreetmap.org/export/embed.html?bbox=89.9139171%2C48.9600524%2C89.9339171%2C48.9720524&layer=mapnik&marker=48.9660524%2C89.9239171",
      locale: "mn",
      favicon: "/images/favicon.ico",
      agenda: [
        {
          title: "Хурим",
          date: "2026-06-24",
          startTime: "18:00",
          endTime: "00:00",
          location: '"Sky Palace" Хуримын ордон',
          address: 'Монгол, Баян-Өлгий, "Sky Palace" Хуримын ордон',
        },
      ],
      audio: {
        src: "/audio/toi.mp3",
        title: "Хуримын дуу",
        autoplay: true,
        loop: true,
        toastDuration: 3000,
      },
      gifts: {
        accounts: [
          {
            bank: "Kaspi Bank",
            accountName: "Bekbolat",
            accountNumber: "0000 0000 0000 0000",
          },
        ],
      },
      shareImages: {
        ogImage: "/images/Ai.jfif",
        thumbnail: "/images/ai2.jfif",
        couplePhoto: "/images/Ai.jfif",
        banner: "/images/ai2.jfif",
        invitation: "/images/Ai.jfif",
      },
    },
  },
};

export default configs;
